<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ClientNetworkLib.CSharp</RootNamespace>
    <AssemblyName>ClientNetworkLib.CSharp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PacketRuntime.CSharp\PacketRuntime.CSharp.csproj" />
  </ItemGroup>

</Project>
