/*
	Server Config File
		* WorldServer 초기 실행용 설정
		* 인코딩은 UTF-16 LE로 설정하는 것이 원칙이지만,
		* 현재 저장소 기준 skeleton 단계에서는 기존 값과 동일한 설정을 유지한다.
*/

Server:
	- IP = 0.0.0.0;
	- PORT = 10611;
	- PACKET_KEY = 50;
	- PACKET_CODE = 119;

	- IOCP_WORKER_THREAD = 16;
	- IOCP_ACTIVE_THREAD = 4;
	- USE_ZERO_COPY = 0;
	- MAX_SESSION_COUNT = 6000;
	- ACCEPTEX_COUNT = 4;
	- CONTENTS_THREAD_COUNT = 4;
	- MAX_CONTENTS_FPS = 25;
	- DELAY_FRAME = 3;

WorldServer:
	- ENTRANCE_FPS = 25;
