<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RootNamespace>Generated.Packets</RootNamespace>
    <AssemblyName>Generated.Packets.CSharp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PacketRuntime.CSharp\PacketRuntime.CSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Generated\CSharp\Packets\**\*.cs" Link="Generated\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
