using System.Text;

internal static class CSharpPacketGenerator
{
    public static string GeneratePacketsFile(PacketSchemaDocument document)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using PacketRuntime.CSharp;");
        builder.AppendLine();
        builder.AppendLine($"namespace Generated.Packets.{document.Content}");
        builder.AppendLine("{");
        builder.AppendLine($"\tpublic static class {document.Content}PacketOpcodes");
        builder.AppendLine("\t{");

        foreach (PacketSchemaMessage message in document.Messages)
        {
            AppendOpcodeConstant(builder, message.Name, "Rq", message.Rq);
            AppendOpcodeConstant(builder, message.Name, "Rp", message.Rp);
            AppendOpcodeConstant(builder, message.Name, "Noti", message.Noti);
            AppendOpcodeConstant(builder, message.Name, "Broadcast", message.Broadcast);
        }

        builder.AppendLine("\t}");
        builder.AppendLine();

        foreach (PacketSchemaMessage message in document.Messages)
        {
            AppendPacketClass(builder, document.Content, message.Name, "Rq", message.Rq);
            AppendPacketClass(builder, document.Content, message.Name, "Rp", message.Rp);
            AppendPacketClass(builder, document.Content, message.Name, "Noti", message.Noti);
            AppendPacketClass(builder, document.Content, message.Name, "Broadcast", message.Broadcast);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    public static string GenerateRegistryFile(IReadOnlyList<PacketSchemaDocument> documents)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using PacketRuntime.CSharp;");
        builder.AppendLine();
        builder.AppendLine("namespace Generated.Packets");
        builder.AppendLine("{");
        builder.AppendLine("\tpublic sealed class GeneratedPacketRegistry : IContentPacketRegistry");
        builder.AppendLine("\t{");
        builder.AppendLine("\t\tpublic IContentPacket? CreatePacket(ushort opcode)");
        builder.AppendLine("\t\t{");
        builder.AppendLine("\t\t\tswitch (opcode)");
        builder.AppendLine("\t\t\t{");

        foreach (PacketSchemaDocument document in documents)
        {
            foreach (PacketSchemaMessage message in document.Messages)
            {
                AppendRegistryCase(builder, document.Content, message.Name, "Rq", message.Rq);
                AppendRegistryCase(builder, document.Content, message.Name, "Rp", message.Rp);
                AppendRegistryCase(builder, document.Content, message.Name, "Noti", message.Noti);
                AppendRegistryCase(builder, document.Content, message.Name, "Broadcast", message.Broadcast);
            }
        }

        builder.AppendLine("\t\t\tdefault:");
        builder.AppendLine("\t\t\t\treturn null;");
        builder.AppendLine("\t\t\t}");
        builder.AppendLine("\t\t}");
        builder.AppendLine("\t}");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendOpcodeConstant(StringBuilder builder, string messageName, string kindSuffix, PacketSchemaEndpoint? endpoint)
    {
        if (endpoint == null)
        {
            return;
        }

        builder.AppendLine($"\t\tpublic const ushort {BuildOpcodeConstantName(messageName, kindSuffix)} = {endpoint.Opcode};");
    }

    private static void AppendRegistryCase(StringBuilder builder, string contentName, string messageName, string kindSuffix, PacketSchemaEndpoint? endpoint)
    {
        if (endpoint == null)
        {
            return;
        }

        string packetClassName = BuildPacketClassName(messageName, kindSuffix);
        string opcodeConstantName = BuildOpcodeConstantName(messageName, kindSuffix);
        builder.AppendLine($"\t\t\tcase {contentName}.{contentName}PacketOpcodes.{opcodeConstantName}:");
        builder.AppendLine($"\t\t\t\treturn new {contentName}.{packetClassName}();");
    }

    private static void AppendPacketClass(StringBuilder builder, string contentName, string messageName, string kindSuffix, PacketSchemaEndpoint? endpoint)
    {
        if (endpoint == null)
        {
            return;
        }

        string packetClassName = BuildPacketClassName(messageName, kindSuffix);
        string opcodeConstantName = BuildOpcodeConstantName(messageName, kindSuffix);
        builder.AppendLine($"\tpublic sealed partial class {packetClassName} : IContentPacket");
        builder.AppendLine("\t{");
        builder.AppendLine($"\t\tpublic ushort Opcode => {contentName}PacketOpcodes.{opcodeConstantName};");
        builder.AppendLine();

        foreach (PacketSchemaField field in endpoint.Fields)
        {
            string propertyType = PacketTypeMapping.RenderCSharpType(field.Type);
            string propertyName = ToPascalCase(field.Name);
            string initializer = RenderPropertyInitializer(SchemaTypeParser.Parse(field.Type));
            builder.AppendLine($"\t\tpublic {propertyType} {propertyName} {{ get; set; }}{initializer}");
        }

        if (endpoint.Fields.Count > 0)
        {
            builder.AppendLine();
        }

        builder.AppendLine("\t\tpublic void Serialize(PacketWriter writer)");
        builder.AppendLine("\t\t{");
        foreach (PacketSchemaField field in endpoint.Fields)
        {
            AppendSerializeNode(builder, SchemaTypeParser.Parse(field.Type), ToPascalCase(field.Name), 3);
        }
        builder.AppendLine("\t\t}");
        builder.AppendLine();
        builder.AppendLine("\t\tpublic bool Deserialize(PacketReader reader)");
        builder.AppendLine("\t\t{");
        foreach (PacketSchemaField field in endpoint.Fields)
        {
            AppendDeserializeNode(builder, SchemaTypeParser.Parse(field.Type), ToPascalCase(field.Name), BuildVariableName(field.Name), 3);
        }
        builder.AppendLine("\t\t\treturn reader.IsAtEnd;");
        builder.AppendLine("\t\t}");
        builder.AppendLine("\t}");
        builder.AppendLine();
    }

    private static void AppendSerializeNode(StringBuilder builder, SchemaTypeNode typeNode, string valueExpression, int indentLevel)
    {
        string indent = new string('\t', indentLevel);
        switch (typeNode.Name)
        {
            case "bool":
                builder.AppendLine($"{indent}writer.WriteBoolean({valueExpression});");
                return;
            case "int8":
                builder.AppendLine($"{indent}writer.WriteSByte({valueExpression});");
                return;
            case "uint8":
                builder.AppendLine($"{indent}writer.WriteByte({valueExpression});");
                return;
            case "int16":
                builder.AppendLine($"{indent}writer.WriteInt16({valueExpression});");
                return;
            case "uint16":
                builder.AppendLine($"{indent}writer.WriteUInt16({valueExpression});");
                return;
            case "int32":
                builder.AppendLine($"{indent}writer.WriteInt32({valueExpression});");
                return;
            case "uint32":
                builder.AppendLine($"{indent}writer.WriteUInt32({valueExpression});");
                return;
            case "int64":
                builder.AppendLine($"{indent}writer.WriteInt64({valueExpression});");
                return;
            case "uint64":
                builder.AppendLine($"{indent}writer.WriteUInt64({valueExpression});");
                return;
            case "float":
                builder.AppendLine($"{indent}writer.WriteSingle({valueExpression});");
                return;
            case "double":
                builder.AppendLine($"{indent}writer.WriteDouble({valueExpression});");
                return;
            case "string":
            case "string_view":
                builder.AppendLine($"{indent}writer.WriteString({valueExpression});");
                return;
            case "bytes":
            case "bytes_view":
                builder.AppendLine($"{indent}writer.WriteBytes({valueExpression});");
                return;
            case "vector":
                builder.AppendLine($"{indent}writer.WriteUInt32((uint){valueExpression}.Count);");
                builder.AppendLine($"{indent}for (int index = 0; index < {valueExpression}.Count; ++index)");
                builder.AppendLine($"{indent}{{");
                AppendSerializeNode(builder, typeNode.TypeArguments[0], $"{valueExpression}[index]", indentLevel + 1);
                builder.AppendLine($"{indent}}}");
                return;
            case "array":
                string arrayLength = typeNode.LiteralArguments[0];
                builder.AppendLine($"{indent}for (int index = 0; index < {arrayLength}; ++index)");
                builder.AppendLine($"{indent}{{");
                AppendSerializeNode(builder, typeNode.TypeArguments[0], $"{valueExpression}[index]", indentLevel + 1);
                builder.AppendLine($"{indent}}}");
                return;
            case "map":
            case "unordered_map":
                builder.AppendLine($"{indent}writer.WriteUInt32((uint){valueExpression}.Count);");
                builder.AppendLine($"{indent}foreach (KeyValuePair<{PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])}, {PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[1])}> entry in {valueExpression})");
                builder.AppendLine($"{indent}{{");
                AppendSerializeNode(builder, typeNode.TypeArguments[0], "entry.Key", indentLevel + 1);
                AppendSerializeNode(builder, typeNode.TypeArguments[1], "entry.Value", indentLevel + 1);
                builder.AppendLine($"{indent}}}");
                return;
            default:
                throw new InvalidOperationException($"Unsupported C# serialization schema type: {typeNode.OriginalText}");
        }
    }

    private static void AppendDeserializeNode(StringBuilder builder, SchemaTypeNode typeNode, string targetExpression, string variablePrefix, int indentLevel)
    {
        string indent = new string('\t', indentLevel);
        switch (typeNode.Name)
        {
            case "bool":
                builder.AppendLine($"{indent}if (!reader.TryReadBoolean(out bool {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "int8":
                builder.AppendLine($"{indent}if (!reader.TryReadSByte(out sbyte {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "uint8":
                builder.AppendLine($"{indent}if (!reader.TryReadByte(out byte {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "int16":
                builder.AppendLine($"{indent}if (!reader.TryReadInt16(out short {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "uint16":
                builder.AppendLine($"{indent}if (!reader.TryReadUInt16(out ushort {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "int32":
                builder.AppendLine($"{indent}if (!reader.TryReadInt32(out int {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "uint32":
                builder.AppendLine($"{indent}if (!reader.TryReadUInt32(out uint {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "int64":
                builder.AppendLine($"{indent}if (!reader.TryReadInt64(out long {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "uint64":
                builder.AppendLine($"{indent}if (!reader.TryReadUInt64(out ulong {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "float":
                builder.AppendLine($"{indent}if (!reader.TryReadSingle(out float {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "double":
                builder.AppendLine($"{indent}if (!reader.TryReadDouble(out double {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "string":
            case "string_view":
                builder.AppendLine($"{indent}if (!reader.TryReadString(out string {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "bytes":
            case "bytes_view":
                builder.AppendLine($"{indent}if (!reader.TryReadBytes(out byte[] {variablePrefix}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression} = {variablePrefix};");
                return;
            case "vector":
                string listCountName = $"{variablePrefix}Count";
                string listItemName = $"{variablePrefix}Item";
                builder.AppendLine($"{indent}if (!reader.TryReadCount(out int {listCountName}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression}.Clear();");
                builder.AppendLine($"{indent}if ({targetExpression}.Capacity < {listCountName})");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\t{targetExpression}.Capacity = {listCountName};");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}for (int index = 0; index < {listCountName}; ++index)");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\t{PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])} {listItemName} = {RenderLocalInitializer(typeNode.TypeArguments[0])};");
                AppendDeserializeNode(builder, typeNode.TypeArguments[0], listItemName, $"{listItemName}Read", indentLevel + 1);
                builder.AppendLine($"{indent}\t{targetExpression}.Add({listItemName});");
                builder.AppendLine($"{indent}}}");
                return;
            case "array":
                string arrayLength = typeNode.LiteralArguments[0];
                string arrayItemName = $"{variablePrefix}Item";
                builder.AppendLine($"{indent}if ({targetExpression}.Length != {arrayLength})");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\t{targetExpression} = new {PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])}[{arrayLength}];");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}for (int index = 0; index < {arrayLength}; ++index)");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\t{PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])} {arrayItemName} = {RenderLocalInitializer(typeNode.TypeArguments[0])};");
                AppendDeserializeNode(builder, typeNode.TypeArguments[0], arrayItemName, $"{arrayItemName}Read", indentLevel + 1);
                builder.AppendLine($"{indent}\t{targetExpression}[index] = {arrayItemName};");
                builder.AppendLine($"{indent}}}");
                return;
            case "map":
            case "unordered_map":
                string mapCountName = $"{variablePrefix}Count";
                string keyType = PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0]);
                string valueType = PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[1]);
                string keyName = $"{variablePrefix}Key";
                string valueName = $"{variablePrefix}Value";
                builder.AppendLine($"{indent}if (!reader.TryReadCount(out int {mapCountName}))");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\treturn false;");
                builder.AppendLine($"{indent}}}");
                builder.AppendLine($"{indent}{targetExpression}.Clear();");
                builder.AppendLine($"{indent}for (int index = 0; index < {mapCountName}; ++index)");
                builder.AppendLine($"{indent}{{");
                builder.AppendLine($"{indent}\t{keyType} {keyName} = {RenderLocalInitializer(typeNode.TypeArguments[0])};");
                AppendDeserializeNode(builder, typeNode.TypeArguments[0], keyName, $"{keyName}Read", indentLevel + 1);
                builder.AppendLine($"{indent}\t{valueType} {valueName} = {RenderLocalInitializer(typeNode.TypeArguments[1])};");
                AppendDeserializeNode(builder, typeNode.TypeArguments[1], valueName, $"{valueName}Read", indentLevel + 1);
                builder.AppendLine($"{indent}\t{targetExpression}[{keyName}] = {valueName};");
                builder.AppendLine($"{indent}}}");
                return;
            default:
                throw new InvalidOperationException($"Unsupported C# deserialization schema type: {typeNode.OriginalText}");
        }
    }

    private static string RenderPropertyInitializer(SchemaTypeNode typeNode)
    {
        return typeNode.Name switch
        {
            "string" or "string_view" => " = string.Empty;",
            "bytes" or "bytes_view" => " = Array.Empty<byte>();",
            "vector" => $" = new List<{PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])}>();",
            "array" => $" = new {PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])}[{typeNode.LiteralArguments[0]}];",
            "map" or "unordered_map" => $" = new Dictionary<{PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])}, {PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[1])}>();",
            _ => string.Empty
        };
    }

    private static string RenderLocalInitializer(SchemaTypeNode typeNode)
    {
        return typeNode.Name switch
        {
            "string" or "string_view" => "string.Empty",
            "bytes" or "bytes_view" => "Array.Empty<byte>()",
            "vector" => $"new List<{PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])}>()",
            "array" => $"new {PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])}[{typeNode.LiteralArguments[0]}]",
            "map" or "unordered_map" => $"new Dictionary<{PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[0])}, {PacketTypeMapping.RenderCSharpType(typeNode.TypeArguments[1])}>()",
            _ => "default!"
        };
    }

    private static string BuildPacketClassName(string messageName, string kindSuffix)
    {
        return kindSuffix switch
        {
            "Broadcast" => $"{messageName}BroadcastPacket",
            _ => $"{messageName}{kindSuffix}Packet"
        };
    }

    private static string BuildOpcodeConstantName(string messageName, string kindSuffix)
    {
        return kindSuffix switch
        {
            "Broadcast" => $"{messageName}Broadcast",
            _ => $"{messageName}{kindSuffix}"
        };
    }

    private static string ToPascalCase(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "Value";
        }

        if (value.Contains('_'))
        {
            string[] parts = value.Split('_', StringSplitOptions.RemoveEmptyEntries);
            var builder = new StringBuilder();
            foreach (string part in parts)
            {
                builder.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                {
                    builder.Append(part[1..]);
                }
            }

            return builder.Length == 0 ? "Value" : builder.ToString();
        }

        return char.ToUpperInvariant(value[0]) + value[1..];
    }

    private static string BuildVariableName(string fieldName)
    {
        string pascalCase = ToPascalCase(fieldName);
        return char.ToLowerInvariant(pascalCase[0]) + pascalCase[1..] + "Value";
    }
}
