<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ChattingClientWinForms</RootNamespace>
    <AssemblyName>ChattingClientWinForms</AssemblyName>
    <BaseOutputPath>..\..\Out\ChattingClientWinForms\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\ClientNetworkLib.CSharp\ClientNetworkLib.CSharp.csproj" />
    <ProjectReference Include="..\..\Libraries\GeneratedPackets.CSharp\GeneratedPackets.CSharp.csproj" />
  </ItemGroup>

</Project>
